repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.280'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: test.*
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: test.*
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: test.*
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "^tests/resources/"
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ["gibberish-detector"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["pydantic<2.0", "toml", "types-all"]
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        exclude: test.*|cli\.py
        args:
          - -v 2
          - "--message-template={path}:{line} in `{obj}`:\n        {msg_id}: {msg}"
          - --strictness=short
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        exclude: test.*
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-azure-pipelines
